---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: chef/centos-6.6

suites:
  - name: default
    run_list:
      - recipe[sandy::default]
    attributes:
      sandy:
        storage:
          actions: ['nothing']
        worker:
          data_bag: 'sandy-utils-kitchen'
  - name: worker
    run_list:
      - recipe[sandy::database]
      - recipe[sandy::redis]
      - recipe[sandy::worker]
    attributes:
      sandy:
        storage:
          actions: ['nothing']
  - name: web
    run_list:
      - recipe[sandy::database]
      - recipe[sandy::redis]
      - recipe[sandy::web]
    attributes:
      sandy:
        storage:
          actions: ['nothing']
